Roles Management
KnowageLabs/Knowage-Server pull request #184
Opened 2021-06-02 14:33 UTC by dbulatovicx32

Roles Management v1.0 with changes after peer review.

I have read the CLA Document and I hereby sign the CLA

2021-06-07 16:02 UTC, Redjaw requested changes

2021-06-08 08:05 UTC, dbulatovicx32 commented on knowage-vue/src/i18n/en_US.json
> +                "description": "Description",
Am i looking only at these 4 or all of labels in Roles Management?
From these 4 only **"name": "Name"** can be removed.

2021-06-08 08:07 UTC, Redjaw commented on knowage-vue/src/i18n/en_US.json
> +                "description": "Description",
The lowercase/uppercase management will be on the css side. If the translation is already present in common please use that one.

2021-06-08 08:35 UTC, dbulatovicx32 commented on knowage-vue/src/i18n/en_US.json
> +                "description": "Description",
I have made the changes for the duplicate fields (those that i could find), if you find any more, please notify me.

2021-06-08 09:50 UTC, Redjaw approved these changes

2021-06-28 10:17 UTC, merged