Functionalities Management v1.0
KnowageLabs/Knowage-Server pull request #201
Opened 2021-07-08 14:43 UTC by dbulatovicx32

Changes after peer review:

1. Fixed padding on list view when hovering over items
2. Added :disabled button property if all 4 checkboxes are locked

I have read the CLA Document and I hereby sign the CLA

2021-07-15 10:15 UTC, Redjaw requested changes

2021-07-15 10:26 UTC, BojanSovticEngIT commented on knowage-vue/public/data/demo_data.json
> +[{"biObjects":[],"codType":"LOW_FUNCT","description":"Analisi Dati BDRP - DEF","id":69,"name":"Analisi Dati BDRP - DEF","parentId":1,"path":"/Functionalities/Analisi Dati BDRP - DEF","code":"Analisi
It is just mock data from as-latest, i forgot to delete it, sorry

2021-07-15 10:42 UTC, Redjaw commented on knowage-vue/public/data/demo_data.json
> +[{"biObjects":[],"codType":"LOW_FUNCT","description":"Analisi Dati BDRP - DEF","id":69,"name":"Analisi Dati BDRP - DEF","parentId":1,"path":"/Functionalities/Analisi Dati BDRP - DEF","code":"Analisi
Thank you!

2021-07-21 10:26 UTC, Redjaw approved these changes

2021-07-21 10:29 UTC, merged