Dashboard sprint 7
KnowageLabs/Knowage-Server pull request #768
Opened 2023-02-06 14:48 UTC by BojanSovticEngIT

- Image Widget
- Custom Widget

2023-02-06 17:11 UTC, Redjaw requested changes

2023-02-07 08:23 UTC, BojanSovticEngIT commented on knowage/js/lib/vega-lite/vega-lite.js
> +!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("vega")):"function"==typeof define&&define.amd?define(["exports","vega"],t):t((e="undefined"!=typeof globalThis?g
Can you try it now? I think I removed them all https://github.com/KnowageLabs/Knowage-Server/pull/768/commits/8b63d280a75a79429b96f6114ce5dbb648c66191

2023-02-07 08:46 UTC, Redjaw approved these changes

2023-02-07 08:47 UTC, Redjaw commented on knowage/js/lib/vega-lite/vega-lite.js
> +!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("vega")):"function"==typeof define&&define.amd?define(["exports","vega"],t):t((e="undefined"!=typeof globalThis?g
yes thx!

2023-02-07 08:47 UTC, merged