Bugfix KNOWAGE-8044
KnowageLabs/Knowage-Server pull request #877
Opened 2023-08-28 13:43 UTC by BojanSovticEngIT

Files changed:

- knowagesdk/src/main/webapp/js/cometd/jquery/jquery-2.1.4.js ([7556, 7551]),
- knowagewhatifengine/src/main/webapp/js/src/angular_1.x/scripts/directives/components/TableToolbarRight.js ([216, 255]),
- knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_backwardCompatibility.js ([144]),
- knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_datasetServices.js ([1044]),
- knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_exportWidgetService.js ([89]),
- knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_variableService.js ([88])

2023-08-28 15:11 UTC, davide-zerbetto requested changes

2023-08-28 15:11 UTC, davide-zerbetto commented on knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_backwardCompatibility.js
> +								if(!model.content.columnSelectedOfDataset[k].formula.match(/(AVG|SUM|MIN|MAX|COUNT|COUNT DISTINCT|TOTAL_SUM|TOTAL_AVG|TOTAL_MIN|TOTAL_MAX|TOTAL_COUNT)\("[\D+\-*/\w]*"\)/gm)){
Reg expression logic is not the same as before, please check it

2023-08-28 15:11 UTC, davide-zerbetto commented on knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_datasetServices.js
> +    objString = objString.replace(/\$V\{([a-zA-Z0-9_]+)(?::[a-zA-Z0-9_]+)?}/g,function(match,p1,p2){
Reg expression was changed: "-" has been removed and why adding ":"?

2023-08-28 15:11 UTC, davide-zerbetto commented on knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_exportWidgetService.js
> +  		  objString = objString.replace(/\$V\{([a-zA-Z0-9_]+)(?::[a-zA-Z0-9_]+)?}/g,function(match,p1,p2){
Same as previous comment

2023-08-28 15:11 UTC, davide-zerbetto commented on knowagecockpitengine/src/main/webapp/js/src/angular_1.4/cockpit/services/cockpitModule_variableService.js
> +				tempText = tempText.replace(/\$V\{[a-zA-Z0-9_]+(?::[a-zA-Z0-9_]+)?\}/g,function(match,p1,p2){
Same as previous comment

2023-08-28 15:11 UTC, davide-zerbetto commented on knowagewhatifengine/src/main/webapp/js/src/angular_1.x/scripts/directives/components/TableToolbarRight.js
> +		var regEx = /([A-Z]+(_[A-Z]+)*[A-Z]*)+/g;
Maybe it shoud be /([A-Z_]+)+/g;

2023-08-28 15:11 UTC, davide-zerbetto commented on knowagewhatifengine/src/main/webapp/js/src/angular_1.x/scripts/directives/components/TableToolbarRight.js
> +		var regEx = /([A-Z]+(_[A-Z]+)*[A-Z]*)+/g;
Maybe it shoud be /([A-Z_]+)+/g;

2023-09-07 12:44 UTC, BojanSovticEngIT commented
Updated

2023-09-08 10:47 UTC, BojanSovticEngIT commented
Updated

2023-09-18 15:14 UTC, merged