Update DataSetDAOImpl.java
KnowageLabs/Knowage-Server pull request #896
Opened 2023-10-10 09:41 UTC by BojanSovticEngIT

Part of bugfix:
- [KNOWAGE-8139](https://production.eng.it/jira/browse/KNOWAGE-8139)

Notes:
- **knowagedao/../SbiDataSetDAOImpl.java** - possible false positive, I don't use any parameter directly in the statement string, not sure why is it being reported
- **knowagedao/../DataSetDAOImpl.java** - loadDataSets is marked as deprecated, maybe we don't need it?  The issue is on line 1228. is similar to the one above, I don't see why the statement string is considered unsafe.
							      - Added columnFilter and columnOrdering as named parameters

2023-10-20 09:07 UTC, kerny3d requested changes

2023-11-06 13:49 UTC, BojanSovticEngIT commented on knowagedao/src/main/java/it/eng/spagobi/tools/dataset/dao/DataSetDAOImpl.java
Removed methods.

2023-11-06 13:49 UTC, BojanSovticEngIT commented
Removed methods.

2024-02-01 07:38 UTC, kerny3d approved these changes

2024-03-09 00:30 UTC, closed without merging